---
- name: "Creating Aws Infrastructure"
  hosts: localhost
  connection: local
  vars_files:
     - new.vars
     - credentials.vars

  tasks:

    - name: "KeyPair Creation"
      ec2_key:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "{{ key_name }}"
        state: present
      register: keypair_data

    - name: "KeyPair_saving"
      when: keypair_data.changed == true
      copy:
        content: "{{ keypair_data.key.private_key }}"
        dest: "{{ key_name }}.pem"
        mode: 0400


    - name: "Creating Secutiry Group"
      ec2_group:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        name: "{{ sg_name }}"
        description: "SG created by ansible"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0


          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0


          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

      register: security_group
    - debug:
        var: "security_group.group_id"

    - name: "Creating Launch configuration"
      ec2_lc:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "newlaunch_lc"
        image_id: ami-0233c2d874b811deb
        key_name: "{{ key_name }}"
        security_groups: "{{ security_group.group_id }}"
        instance_type: t2.micro
        user_data_path: userdata.sh
        state: present
      register: launch_status
    - debug:
        var: "launch_status"


    - name: "Creating ELB"
      ec2_elb_lb:
        name: "elb"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        connection_draining_timeout: 60
        cross_az_load_balancing: true
        security_group_ids: "{{ security_group.group_id }}"
        state: present
        zones:
          - "{{ region }}a"
          - "{{ region }}b"
          - "{{ region }}c"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        health_check:
            ping_protocol: http
            ping_port: 80
            ping_path: "/health.html"
            response_timeout: 2
            interval: 10
            unhealthy_threshold: 2
            healthy_threshold: 2
      register: elb_status

    - debug:
        var: "elb_status.elb.dns_name"


    - name: "Autoscaling-Group Creation"
      ec2_asg:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        name: "devops_asg"
        launch_config_name: "newlaunch_lc"
        health_check_period: 30
        health_check_type: EC2
        replace_all_instances: no
        min_size: 2
        max_size: 2
        desired_capacity: 2
        state: present
        tags:
          - Name: devops_asg_servers
            propagate_at_launch: true
      register: autoscaling
    - debug:
        var: "autoscaling"


    - name: "Fetching Ec2 Instance Details"
      ec2_instance_info:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        filters:
          "tag:aws:autoscaling:groupName": "devops_asg"
          instance-state-name: [ "running"]
      register: ec2

    - name: "Creating Dymaic Inventory"
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: "instances"
        ansible_host: "{{ item.public_ip_address }}"
        ansible_port: 22
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{ key_name }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items:
        - "{{ ec2.instances }}"

- name: "Website From GitHub"
  hosts: instances
  become: true
  serial: 1
  vars_files:
    - new.vars
  tasks:

    - name: "Installing Packages"
      yum:
        name:
          - httpd
          - php
          - git
        state: present


    - name: "Cloning Repository from Git"
      git:
        repo: "{{ git_url }}"
        dest: "{{ clone_dir }}"
      register: repo_status

    - name: "Disbaling ELB Health Check"
      when: repo_status.changed == true
      file:
        path: /var/www/html/health.html
        state: touch
        mode: 0000

    - name: "Off loading Ec2-Instance From ELB"
      when: repo_status.changed == true
      pause:
        seconds: "{{ health_time }}"


    - name: "Copying New Content To documentRoot"
      when: repo_status.changed == true
      copy:
        src: "{{ clone_dir }}"
        dest: /var/www/html/
        remote_src: true


    - name: "Restarting/enabling Application"
      when: repo_status.changed == true
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: "Enabling ELB Health Check"
      when: repo_status.changed == true
      file:
        path: "/var/www/html/{{ health_page }}"
        state: touch
        mode: 0644

    - name: "Loading Ec2-Instance to ELB"
      when: repo_status.changed == true
      pause:
        seconds: "{{ health_time }}"
